### PR TITLE
Adds Vienna 2024

### PR DESCRIPTION
**Pull request by andrea-kyurchiev**
Adds the titles and images for Vienna. Dates, schedule etc still need updated

### CODE REVIEW

**Comment by yuhattor** [comment]
Can you minimize the size with some more cropping?
image

**Comment by andrea-kyurchiev** [comment]
@yuhattor if you have the cropped images please post them here so I can download them. I had to screenshot them from the pptx

**Comment by yuhattor** [comment]
fyi! 
https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint

**Comment by andrea-kyurchiev** [comment]
That's the requested image resized @yuhattor

**Comment by yuhattor** [comment]
wow! That's quick!
Thank you!

**Comment by yuhattor** [comment]
LGTM! Thank you for the quick response! Amazing!

**Pull request merged**
