### PR TITLE
chore: add Paris gathering to list of gatherings

### PR DESCRIPTION
**Pull request by andrea-kyurchiev**

### CODE REVIEW

**Comment by yuhattor** [comment]
Thanks, we have to move this to upcoming event listing, from past events!

**Comment by yuhattor** [comment]
Let me work on this

**Comment by andrea-kyurchiev** [comment]
@yuhattor apologies, just moved it there

**Comment by yuhattor** [comment]
Looks good to me!

**Comment by yuhattor** [comment]
Thanks!

**Comment by rrrutledge** [comment]
Great work❗️

**Pull request merged**
