### PR TITLE
Creating Vienna Report

### PR DESCRIPTION
**Pull request by yuhattor**

### CODE REVIEW

**Comment by claredillon** [comment]
Can't seem to edit the file directly - so here are my notes. 

We had a wonderful InnerSource Gathering in Vienna on the first evening of the LF OSS Summit EU in a nearby hotel. 14 people attended - a mix of those already familiar with ISC and some first time attendees. Most had experience and a basic understanding of InnerSource. The unconference style discussion focused on InnerSource incentives (more notes below). 
image

**Comment by claredillon** [comment]
Notes on Incentives:
- No incentive is universal, it is necessary to think about different incentives for different people, to do different things, in different contexts. Related ideas include:
  - We may need different incentives to open repos than to contribute.
  - Think about incentives that are appropriate when program is young (supporting post for sapling) vs scaling (more fertilizer for growing tree). 
- Focus on incentives that bolster respect/status rather than cash rewards can be very impactful. Related ideas include:
  - Incentives that demonstrate influence within an org or group
  - InnerSource awards to drive recognition of activity
  - Giving names of top contributors to management for recognition.
- Building feelings of belonging, building relationships and networking opportunities and new learning experiences can be incentives within themselves (reported as top individual motivations in State of InnerSource Survey). Related ideas include:
  -  Funding / opportunities to meet project maintainers in person. 
  - Funding to attend conferences as rewards. 
- The idea that InnerSource experience == horizontal experience within an org can be tied to promotion pathways (and HR likes having an objective measure of that). 
 
Things that influence management buy-in:
- Outside in ("Other orgs like us are doing this, so we should too").
- Check box metrics - may not be sustainable, but does build awareness of InnerSource in general
-  Solution for talent management (see point about InnerSource experience above)
- Learning & Development option (for those wanting alternative L&D strategies that cost less than training). 
- Architecture Guidelines can influence adoption of InnerSource 
-  InnerSource outcomes that come with funding (e.g. Our source code is used by X groups, we should get more funding). 
- We discussed how discussions of savings related to InnerSource can be counter-productive, because those savings are always eaten by other things, so never appear in the bottom line accounting. Related ideas:
  - Talk to your Finance Team to see how to measure
  - Perhaps look to show how you can deliver more, faster rather than save money.
  - De-duplication as a concept does work/resonate, even if the $ is not obvious.
  -...As does the idea of "reducing complexity of software security pipeline. 
-  The "InnerSource counter" first heard of in NAB Community call
  -  virtual "bank account" of savings made
  - Estimate how much was required to develop InnerSource project
  -  Credit Virtual "bank account" everytime it is used
  -  Perhaps discount for cost of integration and other costs... 
  - It acts as indicator of $ saved, even if that is not visible in accounts.

**Comment by yuhattor** [comment]
Thank you for providing the report!

**Comment by yuhattor** [comment]
@claredillon Could you check the report? 
The visual is [here](https://github.com/InnerSourceCommons/gatherings/blob/reports/vienna/landing-page/content/en/reports/vienna-2024.md)

I added summary on the note section!

**Comment by claredillon** [comment]
Hi Yuki - thanks for putting this in.  I'd recommend removing the image from the detailed notes - it reflects the topics we voted on - not the incentives discussion.

**Comment by claredillon** [comment]
Otherwise - looks good to me!

**Comment by yuhattor** [comment]
Thank you!

**Comment by yuhattor** [comment]
I will merge it!

**Pull request merged**
